<template>
  <Teleport to="body">
    <Modal :open="showModal" @modalClose="$emit('modalClose')">
      <template #header >
        <div class="flex flex-col md:flex-row space-x-2 text-gray-800">
          <span class="text-gray-600">
            Pick List
          </span>
        </div>
      </template>
      <template #default>
        <div>
          <div class="mt-2 border-t border-gray-100">
            <dl class="divide-y divide-gray-100">
              <div class="px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-2 sm:px-0">
                <dt class="text-sm font-medium leading-6 text-gray-900">Generated By</dt>
                <dd class="mt-1 mb-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                  {{ authUser.name }} ({{ now }})
                </dd>
              </div>
              <div class="px-4 py-3 sm:grid sm:grid-cols-3 sm:gap-2 sm:px-0">
                <dt class="text-sm font-medium leading-6 text-gray-900">Machine(s)</dt>
                <dd class="mt-1 mb-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                  <span v-for="(vend, vendIndex) in vends" class="flex flex-col space-y-1">
                    <span>
                      <span class="text-blue-700">
                        {{ vend.code }}
                      </span>
                      -
                      <span v-if="vend.person_id">
                        {{ vend.customer_code }}
                      </span>
                      -
                      <span>
                        {{ vend.customer_name }}
                      </span>
                      <br v-if="vendIndex > 0">
                    </span>
                  </span>
                </dd>
              </div>
            </dl>
          </div>
        </div>
        <div class="flex flex-col">
          <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-3 lg:-mx-5">
            <div class="inline-block min-w-full py-2 align-middle md:px-4 lg:px-6">
              <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
                <table class="table-fixed min-w-full divide-y divide-gray-300">
                  <thead class="bg-gray-50">
                    <tr>
                      <th scope="col" class="w-1/12 px-3 py-3.5 text-center text-xs font-semibold text-gray-900">
                        #
                      </th>
                      <th scope="col" class="w-2/12 px-3 py-3.5 text-center text-xs font-semibold text-gray-900">
                        Image
                      </th>
                      <th scope="col" class="w-3/12 px-3 py-3.5 text-center text-xs font-semibold text-gray-900">
                        Product
                      </th>
                      <th scope="col" class="w-1/12 px-3 py-3.5 text-center text-xs font-semibold text-gray-900">
                        Needed Qty
                      </th>
                    </tr>
                  </thead>
                  <tbody class="bg-white">
                    <tr v-for="(item, itemIndex) in items" :key="item.id" :class="itemIndex % 2 === 0 ? undefined : 'bg-gray-50'">
                      <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-semibold sm:pl-6 text-center text-gray-900">
                        {{ itemIndex + 1 }}
                      </td>
                      <td class="whitespace-nowrap text-sm  font-semibold text-gray-900 text-center">
                        <div class="flex justify-center items-center">
                          <img class="h-16 w-16 rounded-full" :src="item.product.thumbnail.full_url" alt="" v-if="item.product && item.product.thumbnail"/>
                        </div>
                      </td>
                      <td class="py-4 text-sm font-semibold text-center text-gray-800">
                        <span v-if="item.product && item.product.code">
                          {{ item.product.code }}
                        </span>
                        <span class="break-normal text-xs" v-if="item.product && item.product.name">
                          <br> {{ item.product.name }}
                        </span>
                      </td>
                      <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium sm:pl-6 text-center text-blue-600">
                        {{ item.topup_qty }}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </template>
    </Modal>
  </Teleport>
</template>

<script setup>
import { ChevronDoubleDownIcon, ChevronDoubleUpIcon, CheckCircleIcon, PencilSquareIcon } from '@heroicons/vue/20/solid';
import Button from '@/Components/Button.vue';
import Modal from '@/Components/Modal.vue';
import { onMounted, ref } from 'vue';
import { router, usePage } from '@inertiajs/vue3';
const props = defineProps({
  pickLists: Object,
  showModal: Boolean,
})

const authUser = usePage().props.auth.user
const items = ref([])
const vends = ref([])
const now = ref(moment().format('YYMMDD hh:mm A'))
const operatorCountry = usePage().props.auth.operatorCountry
const permissions = usePage().props.auth.permissions

onMounted(() => {
  items.value = props.pickLists.items
  vends.value = props.pickLists.vends
})
const emit = defineEmits(['modalClose'])

function formatDatetime(value) {
  return moment(value).format('YYMMDD hh:mm A');
}
</script>